### ISSUE TITLE
Ability to specify the file name to be served with the server program

### ISSUE THREAD

**Issue by Zero3K** [taimoorjassal/Reliable-File-Transfer-Using-UDP#2]
It would be nice if that was added to it.

**Comment by taimoorjassal** [comment]
File name is defined in the client code already. The program only starts transfer if the particular file exists in the directory.

**Comment by Zero3K** [comment]
I mean, specify it via a command line parameter.

**Comment by taimoorjassal** [comment]
Yes it can be done but it required some extra work to tackle invalid file name parameters plus this was not actually the requirement for the project I coded this for.
